---

- name: ensure all nodes join master cluster
  hosts: master
  tasks:
   - name: Get command to join
     command: kubeadm token create --print-join-command
     register: join_command
   - name: Store command in a file
     copy:
      content: "{{ join_command.stdout }}"
      dest: /tmp/join.sh
   - name: Get Join Script
     fetch:
      src: /tmp/join.sh
      dest: result
- name: run command on nodes
  hosts: nodes
  vars:
   master_host: "{{ groups['master'][0] }}"
  tasks:
   - name: Join cluster
     script: result/{{ master_host }}/tmp/join.sh
     become: true
     ignore_errors: true     
- name: List nodes
  hosts: master
  tasks:
   - name: print nodes
     command: kubectl get nodes
     register: cmd_listnodes
   - name: debug out
     debug: var=cmd_listnodes  
   