---
- name: Ensure sysctl configuration
  hosts: all
  tasks:
   - name: set net.bridge.bridge-nf-call-iptables to 1
     ansible.posix.sysctl: 
      name: net.bridge.bridge-nf-call-iptables 
      value: "1" 
      sysctl_set: true 
      state: present 
      reload: yes
     become: true
     ignore_errors: true
   - name: net ipv4 forward to 1
     ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
     become: yes
   - name: bridge config ip6tables
     ansible.posix.sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
     become: yes
- name: Load Modules
  hosts: all
  tasks:
   - name: Load overlay
     community.general.modprobe:
      name: overlay
      state: present
     become: yes
   - name: Load br_netfilter
     community.general.modprobe:
      name: br_netfilter
      state: present
     become: yes